# Generated by Django 4.1.7 on 2023-03-11 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('Current Account', 'Current Account'), ('Savings Account', 'Savings Account')], max_length=15)),
                ('bank', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_bank_account',
            },
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('bank', 'account_number'), name='unique_bank_account'),
        ),
    ]
